version: '3.9'


services:
  postgres:
    container_name: postgres-template
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: template
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root # 1234
    ports:
      - "5432:5432"
    volumes:
      - './db/postgres/data:/var/lib/postgresql/data'
  
  redis:
    container_name: redis-template
    image: redis:latest
    restart: unless-stopped
    ports:
      - '6379:6379'